site_name: NextUI Docs
site_url: https://nextui.loveretro.games
repo_url: https://github.com/LoveRetro/NextUI
edit_uri: https://github.com/LoveRetro/nextui-wiki/edit/main/docs/
repo_name: LoveRetro/NextUI
copyright: © 2025 NextUI Contributors

theme:
  name: material
  custom_dir: docs/_marketing
  logo: _inc/images/nextui-logo.png
  favicon: _inc/images/favicon.png
  font:
    text: Raleway
    code: Fira Code
  icon:
    admonition:
      warning: octicons/alert-24
      info: octicons/info-24
      example: octicons/sparkles-fill-24
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: nextui-wiki-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: nextui-wiki-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - search.suggest
    - content.tooltips
    - content.code.copy
    - content.code.annotate

extra_css:
  - _inc/css/custom.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LoveRetro/NextUI
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HKd7wqZk3h

  urls:
    discord: https://discord.gg/HKd7wqZk3h
    github: https://github.com/LoveRetro/NextUI

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 3
      permalink: 🔗

plugins:
  - search
  - macros

nav:
  - Docs Home: docs.md
  - Getting Started:
      - getting-started/index.md
      - Installation: getting-started/installation.md
      - Updating: getting-started/updating.md
      - Adding ROMs: getting-started/roms.md
      - Required BIOS: getting-started/bios.md
      - Managing Saves: getting-started/managing-saves.md
      - Managing Cheats: getting-started/cheats.md
  - Customizing:
      - LEDs: customizing/leds.md
      - Overlays: customizing/theming/overlays.md
      - Emulator Icons: customizing/theming/emulator-icons.md
      - Game Artwork: customizing/game-artwork.md
  - Paks:
      - paks/index.md
      - Community Favorites: paks/community-favorites.md
      - Standalone Emulators: paks/standalone-emulators.md
      - Making a Pak: paks/making-a-pak.md
  - Support:
      - Frequently Asked Questions: support/faq.md
  - NextUI Homepage:
      - index.md
