name: Build and Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: bun install
        working-directory: ./marketing
      - run: bun run build
        working-directory: ./marketing

      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry env use /usr/bin/python3

      - run: poetry sync
      - run: poetry env activate

      - run: poetry run mkdocs gh-deploy --force